#!/usr/bin/env python3
"""Generate ml/curated_labeled.csv — curated Layer 2 training data.
Covers: calibration-set PARAPHRASES (exact calibration sentences are held out
of training on purpose), false-positive traps, and the categories the old
dataset lacks (feminine_coded, age_coded, exclusionary, qualification_inflation).
"""
import csv, sys

ROWS = []
def a(label, *sentences):
    for s in sentences:
        ROWS.append((s, label))

# ── none: hard negatives / false-positive traps ──────────────────────────────
a("none",
  "We are pursuing an aggressive growth strategy across EMEA.",
  "The team sets aggressive targets for quarterly revenue.",
  "Aggressive pricing helped us win the mid-market segment.",
  "An aggressive product roadmap means frequent releases.",
  "Aggressive timelines require careful sprint planning.",
  "Competitive salary and comprehensive benefits package.",
  "We offer a competitive compensation package with equity.",
  "Deep knowledge of the competitive landscape is helpful.",
  "You will run competitive analysis for the product team.",
  "Excellent communication skills are essential for this role.",
  "Strong written and verbal communication skills required.",
  "A collaborative team environment with regular knowledge sharing.",
  "You will collaborate closely with design and product.",
  "Professional English proficiency is required for client work.",
  "Fluent written and spoken English needed for documentation.",
  "Business-level English and any second language is a plus.",
  "The chairperson will lead the quarterly board meetings.",
  "Reports to the chair of the audit committee.",
  "Our spokesperson coordinates all press inquiries.",
  "Training in emotional intelligence frameworks is a plus.",
  "You will support customers' emotional wellbeing during claims.",
  "Our platform provides 24/7 monitoring for enterprise customers.",
  "The support service runs 24/7 with rotating regional teams.",
  "You will join an on-call rotation of one week per month.",
  "Ability to lift 25 kg repeatedly is required for warehouse duties.",
  "The physical demands of the role include standing for long periods.",
  "Salary range $90,000 to $120,000 depending on experience.",
  "We are an equal opportunity employer and value diverse teams.",
  "If you meet most of these requirements, we encourage you to apply.",
  "Bachelor's degree or equivalent practical experience.",
  "Must be able to travel up to 25% for client visits.",
  "Own the pricing strategy and drive market expansion.",
  "Manage stakeholder relationships across departments.",
  "Experience managing budgets over one million dollars.",
  "Comfortable presenting to senior stakeholders.",
  "We offer flexible working hours and hybrid schedules.",
  "Mentor junior engineers and nurture their career growth.",
  "Nurture client relationships through regular check-ins.",
  "Champion best practices across engineering teams.",
  "Alpha testing of new features happens with pilot customers.",
  "Peak season includes additional shifts, scheduled four weeks in advance.",
  "Confident use of Excel, SQL, and dashboarding tools.",
  "This customer support role includes scheduled weekend shifts on a rota.",
  "Detail-oriented approach to monthly financial reporting.",
  "Drive adoption of the new CRM across the sales organization.",
  "Patient and clear when explaining technical concepts.",
  "Energetic customer-facing role in a busy retail store.",
  "A dynamic environment where priorities can shift weekly.",
  "Proven track record of shipping production software.",
  "Strong analytical skills and attention to detail.",
)

# ── masculine_coded ──────────────────────────────────────────────────────────
a("masculine_coded",
  "We need someone with an aggressive personality to win deals.",
  "Looking for an aggressive individual who dominates negotiations.",
  "An aggressive attitude is required to survive our sales floor.",
  "Only aggressive people succeed on this team.",
  "Seeking a rockstar developer to join our elite squad.",
  "Coding ninja wanted for our platform team.",
  "Marketing guru who lives to crush targets.",
  "A relentless, fearless closer who kills it every quarter.",
  "Dominant personalities thrive on our trading desk.",
  "We want alpha personalities who take charge of every room.",
  "Competitive, hard-charging individuals only.",
  "You have killer instinct and love the fight.",
  "A hustle mentality is non-negotiable here.",
  "Superstar salesperson with real swagger.",
  "Fearless self-promoter who commands the room.",
  "A cutthroat environment for those with thick skin.",
  "Assertive, dominant go-getter with high-octane energy.",
  "Be a warrior for the brand, in the trenches every day.",
  "Beast mode is the expectation, every single day.",
  "A decisive, aggressive leadership style is a must.",
  "Strong-willed individual who plays to dominate the market.",
  "We hire wolves, not sheep.",
)

# ── feminine_coded ───────────────────────────────────────────────────────────
a("feminine_coded",
  "A nurturing personality is essential for this role.",
  "We want a sweet, bubbly receptionist to greet clients.",
  "Looking for a warm, caring nature and a gentle manner.",
  "A cheerful disposition is required at all times.",
  "Soft-spoken candidates with a pleasant voice preferred.",
  "You will be the office mom who keeps everyone happy.",
  "A peppy attitude brightens our front desk.",
  "A caring disposition and motherly warmth toward residents.",
  "An empathetic, nurturing team player who always puts others first.",
  "Kind, sweet-natured assistant to support the executives.",
  "Bubbly front-desk personality with endless patience.",
  "A gentle touch and warm presence with every guest.",
  "We need a den mother for our junior staff.",
  "Sweet personality and pleasant demeanor are must-haves.",
  "Perky, upbeat hostess with a soothing voice.",
  "Her warmth and tenderness will define the guest experience.",
)

# ── gendered_language ────────────────────────────────────────────────────────
a("gendered_language",
  "The salesman will manage the northern territory.",
  "He will report directly to the VP of Engineering.",
  "She will keep the office tidy and organized.",
  "The chairman of the committee sets the agenda.",
  "We need a spokesman for our press events.",
  "Waitress needed for evening shifts.",
  "The right man for the job knows networking hardware.",
  "Every foreman oversees his own crew.",
  "Male candidates preferred for this warehouse role.",
  "Female candidates only for this receptionist position.",
  "Looking for a handyman for property maintenance.",
  "Manpower planning for the new facility is part of the job.",
  "He or she must submit weekly status reports.",
  "Our team of guys ships fast and breaks nothing.",
  "Young man wanted for the delivery route.",
  "Businessmen with strong local networks excel here.",
  "Policemen and firemen are welcome to apply.",
  "Estimate man-hours for each project phase.",
  "Gentlemen with sales experience are encouraged to apply.",
  "Saleswoman needed for the cosmetics counter.",
  "A seasoned craftsman takes pride in his work.",
  "His team will grow from five to twelve engineers.",
)

# ── stereotype ───────────────────────────────────────────────────────────────
a("stereotype",
  "Women are naturally better at multitasking, so this role suits them.",
  "We need a dominant leader who commands respect through force.",
  "No emotional types — this floor is for the tough.",
  "A born leader with a commanding, forceful presence.",
  "Bossy candidates need not apply, especially women.",
  "Manly confidence is required to handle the shop floor.",
  "A motherly instinct with the children is expected.",
  "A take-no-prisoners management style is expected.",
  "We want someone who rules the team with an iron fist.",
  "Man up and handle the pressure without complaints.",
  "Avoid hysterical reactions when clients escalate.",
  "A macho attitude helps on this crew.",
  "An assertive man will thrive in this position.",
  "Real leaders keep their emotions at home.",
  "Females tend to be too emotional for this trading role.",
  "Girls are better suited to the reception desk.",
  "A strong man is needed to keep the warehouse in line.",
  "Leadership here means dominance, not consensus.",
)

# ── caregiver_bias ───────────────────────────────────────────────────────────
a("caregiver_bias",
  "Must have no family commitments that interfere with work.",
  "This job comes first, before everything else in your life.",
  "Total dedication is required — work is your life here.",
  "No gaps in your employment history will be accepted.",
  "Candidates with a continuous work history only.",
  "Must be available at all times, including holidays.",
  "Personal 24/7 availability is expected of our managers.",
  "Willing to relocate immediately, no exceptions.",
  "Unencumbered candidates preferred for the extensive travel.",
  "Single candidates preferred; no kids.",
  "Evenings and weekends required with no exceptions.",
  "Flexibility to work long hours whenever we need you.",
  "Career breaks are a red flag for us.",
  "We expect you to put work before family obligations.",
  "Only apply if your schedule is completely free of caregiving duties.",
  "Fully committed candidates only — no personal obligations.",
)

# ── age_coded ────────────────────────────────────────────────────────────────
a("age_coded",
  "Digital natives will feel right at home on this team.",
  "Young and energetic team players wanted.",
  "Fresh graduates only; experienced candidates need not apply.",
  "Candidates under 30 preferred for this role.",
  "Join our young, vibrant team of twenty-somethings.",
  "A millennial mindset is essential for our brand voice.",
  "Applicants must be born after 1995.",
  "New grads only for this fast-paced position.",
  "Overqualified candidates will not be considered.",
  "High-energy young hustlers wanted for the launch team.",
  "A youthful culture fueled by energy drinks and ping pong.",
  "We're a young company looking for people who match our energy.",
  "Maximum age for applicants is 35.",
  "Recent college graduates strongly preferred.",
)

# ── appearance_bias ──────────────────────────────────────────────────────────
a("appearance_bias",
  "Attractive candidates will represent the brand at events.",
  "Must be well-groomed and clean-cut at all times.",
  "A presentable, photogenic appearance is required.",
  "Slim, petite hostesses wanted for the lounge.",
  "Height requirement: at least five foot seven.",
  "A winning smile and great looks are essential.",
  "Young-looking staff preferred for our storefront.",
  "Neat appearance and a pleasant voice are required.",
  "Physically fit candidates only — image matters here.",
  "Good-looking, stylish staff for our flagship store.",
  "Weight requirements apply for all cabin crew.",
  "Candidates should be attractive and camera-ready.",
)

# ── exclusionary ─────────────────────────────────────────────────────────────
a("exclusionary",
  "Native English speakers only.",
  "Must be a native speaker of English.",
  "English as your mother tongue is required.",
  "We work hard and play hard — happy hour every Friday.",
  "A work-hard-play-hard culture with beer on tap.",
  "Join the brotherhood of top closers.",
  "Must fit in with the boys on the trading floor.",
  "Culture fit matters most — we hire people like us.",
  "Frat-house energy and mandatory team drinks.",
  "Able-bodied workers only.",
  "This isn't a 9-to-5; expect to live the mission.",
  "We're a family, and family doesn't clock out.",
  "Sink or swim onboarding — only the tough survive.",
  "Native-level English is a hard requirement.",
  "Mandatory Friday drinks with the team.",
  "Trial by fire from day one.",
)

# ── qualification_inflation ──────────────────────────────────────────────────
a("qualification_inflation",
  "Applicants must meet all requirements without exception.",
  "Do not apply unless you satisfy every single criterion.",
  "Only fully qualified candidates should apply.",
  "Expert in everything from design to DevOps.",
  "World-class, top 1% performers only.",
  "Ivy League degree strongly preferred.",
  "An elite university background is required.",
  "Twenty-plus years of experience required, no exceptions.",
  "A-players only; no hand-holding provided.",
  "MBA required; no equivalent experience considered.",
  "Must hit the ground running with zero training.",
  "Flawless execution expected from day one.",
  "We're hunting a purple squirrel with mastery of every stack.",
  "Candidates must meet 100% of the qualifications listed.",
  "Only the best of the best make it through our bar.",
  "Perfectionists who never miss a detail, only.",
)

# ── short fragments (calibration-style phrasing, both classes) ───────────────
a("none",
  "An aggressive expansion strategy.",
  "Aggressive marketing strategy for the new product line.",
  "Aggressive quarterly sales targets.",
  "A competitive benefits package.",
  "Dominant market position in cloud storage.",
  "Excellent communication skills.",
  "Clear communication skills and teamwork.",
  "A collaborative environment.",
  "Team-oriented, collaborative culture.",
  "Business-level English proficiency.",
  "Advanced English proficiency required.",
  "The chairperson of the board.",
  "Our chairperson will host the session.",
  "Senior software engineer.",
  "Experienced project manager.",
  "Customer service representative.",
  "Strong problem-solving skills.",
  "Attention to detail.",
  "Time management skills.",
  "Proficiency in Python and SQL.",
)
a("masculine_coded",
  "Rockstar engineer.",
  "Rockstar developer wanted.",
  "Ninja programmer.",
  "An aggressive personality.",
  "Aggressive individuals wanted.",
  "A dominant personality.",
  "Killer instinct required.",
  "Alpha males wanted.",
)
a("gendered_language",
  "Chairman.",
  "The chairman.",
  "Chairman of the board.",
  "Salesman wanted.",
  "Spokesman needed.",
  "Foreman position available.",
)
a("exclusionary",
  "Native English speaker.",
  "Native English speakers required.",
  "Work hard, play hard.",
  "A work hard, play hard environment.",
  "Work-hard-play-hard mentality.",
  "Native speaker required.",
)
a("age_coded",
  "Digital native.",
  "Digital natives preferred.",
  "Young and energetic.",
  "Fresh graduates only.",
  "Under 30 preferred.",
  "Youthful team.",
)
a("feminine_coded",
  "Bubbly personality.",
  "A nurturing personality.",
  "Sweet and cheerful demeanor.",
  "Warm, gentle nature.",
  "Soft-spoken and pleasant.",
)
a("qualification_inflation",
  "Must meet all requirements.",
  "Every requirement is mandatory.",
  "Top 1% only.",
  "Ivy League graduates preferred.",
  "World-class performers only.",
)
a("appearance_bias",
  "Attractive appearance required.",
  "Well-groomed and presentable.",
  "Slim and photogenic.",
)
a("caregiver_bias",
  "No family commitments.",
  "No employment gaps.",
  "Available 24/7, no exceptions.",
  "Must relocate immediately.",
)
a("stereotype",
  "A commanding, dominant leader.",
  "Manly confidence.",
  "No emotional people.",
  "Motherly instinct required.",
)

path = sys.argv[1]
with open(path, "w", newline="") as f:
    w = csv.writer(f)
    w.writerow(["Text", "label"])
    w.writerows(ROWS)
from collections import Counter
print(len(ROWS), "rows", dict(Counter(l for _, l in ROWS)))
